version: "3.10"

services:
  web:
    build:
      context:  .
      dockerfile: Dockerfile
    command:  pytest test_collection.py
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.db
    depends_on:
      - db
    volumes:
      - ./appium-setup:/appium_setup/appium_setup

  db:
    image: postgres
    env_file:
      - .env.db
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: